esphome:
  name: snow_test
  name_add_mac_suffix: true

preferences:
  flash_write_interval: 10min

esp32:
  board: adafruit_feather_esp32s3 #sparkfun_esp32s2_thing_plus
  variant: esp32s3

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  password: ""

ota:
  platform: esphome
  password: ""

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dashboard Fallback Hotspot"
    password: ""

captive_portal:
