esphome:
  name: t-amoled
  platformio_options:
    build_unflags: -Werror=all
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

logger:
  level: DEBUG

api:
  password: ""
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.show: lbl_hastatus
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.hide: lbl_hastatus

ota:
  password: ""
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dashboard Fallback Hotspot"
    password: ""

external_components:
  - source: github://clydebarrow/esphome@amoled
    components: [ qspi_amoled ]
    refresh: 10min
  - source: github://clydebarrow/esphome@cst226
    refresh: 10min
    components: [ cst226 ]
  - source: github://clydebarrow/esphome@lvgl
    refresh: 10min
    components: [ lvgl ]
    
i2c:
  sda: 6
  scl: 7

spi:
  id: quad_spi
  clk_pin: 15
  data_pins:
    - 14
    - 10
    - 16
    - 12

touchscreen:
  - platform: cst226
    id: my_touchscreen
    interrupt_pin: 8
    reset_pin: 17
    transform:
      mirror_x: true
      swap_xy: true      
    
font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 40

      #image:
      #  - file: cat.jpg
      #    id: cat_image
      #    resize: 180x75
      #    type: RGB565
switch:

binary_sensor:

sensor:

number:

light:

select:

output:

display:
  - platform: qspi_amoled
    id: my_display
    data_rate: 80MHz
    model: RM690B0
    dimensions:
      height: 600
      width: 450
      offset_width: 16
        #transform:
        #mirror_x: true
        #swap_xy: true
    color_order: rgb
    brightness: 128
    cs_pin: 11
    reset_pin: 13
    enable_pin: 9
    update_interval: never
    auto_clear_enabled: false


psram:
  mode: octal
  speed: 80MHz

lvgl:
  full_refresh: true
  color_depth: 16
  byte_order: big_endian
  displays:
    - display_id: my_display
  touchscreens:
    - touchscreen_id: my_touchscreen
  top_layer:
    widgets:
      - label:
          text: "\uF1EB"
          id: lbl_hastatus
          hidden: true
          align: top_right
          x: -2
          y: 7
          text_align: right
          text_color: 0x0000ff

  pages:
    - id: main_page
      layout: FLEX
      widgets:
        - btn:
            id: kitchen_off_btn
            align: center
            width: 200
            height: 140
            widgets:
              - label:
                  align: center
                  text: 'Off'
            on_click:
              then:
                - homeassistant.service:
                    service: button.press
                    data:
                      entity_id: button.main_kitchen_position_1_keypad_off
        - btn:
            id: kitchen_bright_btn
            align: center
            width: 200
            height: 140
            widgets:
              - label:
                  align: center
                  text: 'Bright'
            on_click:
              then:
                - homeassistant.service:
                    service: button.press
                    data:
                      entity_id: button.main_kitchen_position_1_keypad_bright
