# Wemos D1/S2
# CN105 Pin:
#   1. n/c (12v)
#   2. Gnd
#   3. vbus (5v)
#   4. Pin 39 (tx from minisplit) (pin 18 on older boards)
#   5. Pin 37 (rx to minisplit) (pin 16 on older boards)
esphome:
  name: mitsubishi
  name_add_mac_suffix: true
  platformio_options:
    build_unflags:
      - "-std=gnu++11"
    build_flags:
      - "-std=gnu++17"

preferences:
  flash_write_interval: 10min

esp32:
  board: lolin_s2_mini
  variant: ESP32S2
  framework:
    type: arduino
    platform_version: 6.4.0

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  password: ""

ota:
  platform: esphome
  password: ""

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dashboard Fallback Hotspot"
    password: ""

captive_portal:

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s

uart:
  id: HP_UART
  rx_pin: 39
  tx_pin: 37
  baud_rate: 2400

climate:
  - platform: cn105
    id: hp
    name: "Heat Pump"
    update_interval: 1500ms # update interval can be adjusted after a first run and logs monitoring
    debounce_delay: 100ms
    icon: mdi:heat-pump
    # Various optional sensors, not all sensors are supported by all heatpumps
    compressor_frequency_sensor:
      name: Compressor Frequency
      entity_category: diagnostic
    outside_air_temperature_sensor:
      name: Outside Air Temp
    vertical_vane_select:
      name: Vertical Vane
    horizontal_vane_select:
      name: Horizontal Vane
    isee_sensor:
      name: ISEE Sensor
    stage_sensor:
      name: Stage
      entity_category: diagnostic
    sub_mode_sensor:
      name: Sub Mode
      entity_category: diagnostic
    auto_sub_mode_sensor:
      name: Auto Sub Mode
      entity_category: diagnostic
