esphome:
  name: snow 
  name_add_mac_suffix: true
    #  platformio_options:
    #    build_unflags:
    #      - "-std=gnu++11"
    #    build_flags:
    #      - "-std=gnu++17"
    #
  includes:
    - tof_vl53l1x.h
  libraries:
    - "Wire"
    - "VL53L1x"

preferences:
  flash_write_interval: 10min

esp32:
  board: sparkfun_esp32s2_thing_plus
  variant: ESP32S2
    #  framework:
    #    type: arduino
    #    platform_version: 6.4.0
    #


# Enable logging
logger:
  #level: VERBOSE

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dashboard Fallback Hotspot"
    password: ""

captive_portal:

i2c:
  sda: 1
  scl: 2
  scan: true
  frequency: 100kHz


# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Uptime
    update_interval: 60s

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s

  - platform: mlx90614
    ambient:
      name: Ambient
    object:
      name: Surface
      emissivity: 0.98  # ~Snow

  - platform: custom
    lambda: |-
      auto my_sensor = new MyCustomSensor();
      App.register_component(my_sensor);
      return {my_sensor};
    sensors:
      name: "Distance"
      accuracy_decimals: 0
      unit_of_measurement: "mm"      
      state_class: "measurement"
      filters:
        - median:
            window_size: 60
            send_every: 60
            send_first_at: 60
